FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "echo '==> ⚙️ Generating Prisma Client...' && npx prisma generate && echo '==> 🗄️ Applying migrations...' && npx prisma migrate deploy && echo '==> 🌱 Seeding database...' && npx prisma db seed && echo '==> 🚀 Starting Next.js dev server...' && npm run dev"]
