import "server-only";

import { prisma } from "@/lib/prisma";

export interface RecordGameSessionInput {
  /** Session ID generated by the plugin, so retries never create duplicates. */
  id: string;
  minecraftUuid: string;
  minecraftUsername: string;
  ipAddress: string;
  connectedAt: Date;
  disconnectedAt: Date;
}

export async function recordGameSession(input: RecordGameSessionInput) {
  const user = await prisma.user.findUnique({
    where: { minecraftUuid: input.minecraftUuid },
    select: { id: true },
  });

  const data = {
    userId: user?.id ?? null,
    minecraftUuid: input.minecraftUuid,
    minecraftUsername: input.minecraftUsername,
    ipAddress: input.ipAddress,
    connectedAt: input.connectedAt,
    disconnectedAt: input.disconnectedAt,
  };

  return prisma.gameSession.upsert({
    where: { id: input.id },
    create: { id: input.id, ...data },
    update: data,
  });
}

export interface GameSessionStats {
  firstConnectedAt: Date | null;
  lastConnectedAt: Date | null;
  totalMinutes: number;
  sessions: {
    id: string;
    minecraftUsername: string;
    ipAddress: string;
    connectedAt: Date;
    disconnectedAt: Date;
    durationMinutes: number;
  }[];
}

/** Playtime is always derived from the recorded session blocks, never stored. */
export async function getGameSessionStats(userId: string): Promise<GameSessionStats> {
  const sessions = await prisma.gameSession.findMany({
    where: { userId },
    orderBy: { connectedAt: "desc" },
  });

  const blocks = sessions.map((session) => ({
    id: session.id,
    minecraftUsername: session.minecraftUsername,
    ipAddress: session.ipAddress,
    connectedAt: session.connectedAt,
    disconnectedAt: session.disconnectedAt,
    durationMinutes: Math.max(
      0,
      Math.round((session.disconnectedAt.getTime() - session.connectedAt.getTime()) / 60000)
    ),
  }));

  return {
    firstConnectedAt: blocks.at(-1)?.connectedAt ?? null,
    lastConnectedAt: blocks[0]?.connectedAt ?? null,
    totalMinutes: blocks.reduce((total, block) => total + block.durationMinutes, 0),
    sessions: blocks,
  };
}
