import { jsonError, jsonOk, readJsonBody, requirePluginAuth } from "@/lib/api/plugin-auth";
import { parseMinecraftUuid } from "@/lib/api/plugin-players";
import { recordGameSession } from "@/lib/services/game-session-service";

const SESSION_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const USERNAME_PATTERN = /^[A-Za-z0-9_]{1,16}$/;

function parseDate(value: unknown): Date | null {
  if (typeof value !== "string") return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

/**
 * Records a closed game session. Idempotent on the session ID generated by the plugin.
 * Body: { id, minecraftUuid, minecraftUsername, ipAddress, connectedAt, disconnectedAt }
 */
export async function POST(request: Request) {
  const unauthorized = requirePluginAuth(request);
  if (unauthorized) return unauthorized;

  const body = await readJsonBody(request);
  if (!body) return jsonError("Corps de requête invalide.", 400);

  const id =
    typeof body.id === "string" && SESSION_ID_PATTERN.test(body.id) ? body.id.toLowerCase() : null;
  const minecraftUuid = parseMinecraftUuid(body.minecraftUuid);
  const minecraftUsername =
    typeof body.minecraftUsername === "string" && USERNAME_PATTERN.test(body.minecraftUsername)
      ? body.minecraftUsername
      : null;
  const ipAddress =
    typeof body.ipAddress === "string" && body.ipAddress.length <= 45 ? body.ipAddress : null;
  const connectedAt = parseDate(body.connectedAt);
  const disconnectedAt = parseDate(body.disconnectedAt);

  if (
    !id ||
    !minecraftUuid ||
    !minecraftUsername ||
    !ipAddress ||
    !connectedAt ||
    !disconnectedAt
  ) {
    return jsonError("Paramètres manquants ou invalides.", 400);
  }
  if (disconnectedAt < connectedAt) {
    return jsonError("La fin de session précède son début.", 400);
  }

  await recordGameSession({
    id,
    minecraftUuid,
    minecraftUsername,
    ipAddress,
    connectedAt,
    disconnectedAt,
  });

  return jsonOk();
}
